/* ==========================================================================
   emoji.js — 1898 biểu tượng Unicode 15.1, 9 nhóm.
   Rút từ emoji-test.txt của Unicode; đã lọc bỏ biến thể màu da và nhóm Component.

   Mỗi mục là [biểu tượng, tên Unicode (tiếng Anh), từ khoá tiếng Việt].
   Từ khoá tiếng Việt dịch theo từng chữ trong tên Unicode nên đọc hơi thô,
   nhưng đủ để gõ tiếng Việt là tìm ra: 1441/1898 mục có từ khoá (76%).
   Ô tìm bỏ dấu hai đầu nên gõ "nha" hay "nhà" đều được, và vẫn tìm được bằng tiếng Anh.
   ========================================================================== */
var EMOJI_GROUPS = [
  { g: "Mặt cười & cảm xúc", items: [
    ["😀","grinning face","cười nhe răng mặt"],["😃","grinning face with big eyes","cười nhe răng mặt có mắt"],
    ["😄","grinning face with smiling eyes","cười nhe răng mặt có mỉm mắt"],
    ["😁","beaming face with smiling eyes","mặt có cười mỉm mắt"],
    ["😆","grinning squinting face","cười nhe răng nheo mắt mặt"],
    ["😅","grinning face with sweat","cười nhe răng mặt có mồ hôi"],
    ["🤣","rolling on the floor laughing","lăn bật"],["😂","face with tears of joy","mặt có nước mắt vui sướng"],
    ["🙂","slightly smiling face","hơi cười mỉm mặt"],["🙃","upside-down face","xuống mặt"],
    ["🫠","melting face","mặt"],["😉","winking face","nháy mắt mặt"],
    ["😊","smiling face with smiling eyes","cười mỉm mặt có mắt"],
    ["😇","smiling face with halo","cười mỉm mặt có"],["🥰","smiling face with hearts","cười mỉm mặt có trái tim"],
    ["😍","smiling face with heart-eyes","cười mỉm mặt có trái tim mắt"],["🤩","star-struck","ngôi sao"],
    ["😘","face blowing a kiss","mặt hôn"],["😗","kissing face","hôn mặt"],["☺️","smiling face","cười mỉm mặt"],
    ["😚","kissing face with closed eyes","hôn mặt có đóng mắt"],
    ["😙","kissing face with smiling eyes","hôn mặt có cười mỉm mắt"],
    ["🥲","smiling face with tear","cười mỉm mặt có nước mắt"],["😋","face savoring food","mặt đồ ăn"],
    ["😛","face with tongue","mặt có lưỡi"],["😜","winking face with tongue","nháy mắt mặt có lưỡi"],
    ["🤪","zany face","mặt"],["😝","squinting face with tongue","nheo mắt mặt có lưỡi"],
    ["🤑","money-mouth face","tiền miệng mặt"],["🤗","smiling face with open hands","cười mỉm mặt có mở bàn tay"],
    ["🤭","face with hand over mouth","mặt có bàn tay trên miệng"],
    ["🫢","face with open eyes and hand over mouth","mặt có mở mắt bàn tay trên miệng"],
    ["🫣","face with peeking eye","mặt có mắt"],["🤫","shushing face","mặt"],["🤔","thinking face","mặt"],
    ["🫡","saluting face","mặt"],["🤐","zipper-mouth face","miệng mặt"],
    ["🤨","face with raised eyebrow","mặt có giơ lên"],["😐","neutral face","mặt"],
    ["😑","expressionless face","mặt"],["😶","face without mouth","mặt không có miệng"],
    ["🫥","dotted line face","chấm mặt"],["😶‍🌫️","face in clouds","mặt"],["😏","smirking face","mặt"],
    ["😒","unamused face","mặt"],["🙄","face with rolling eyes","mặt có lăn mắt"],["😬","grimacing face","mặt"],
    ["😮‍💨","face exhaling","mặt"],["🤥","lying face","mặt"],["🫨","shaking face","bắt tay mặt"],
    ["🙂‍↔️","head shaking horizontally","đầu bắt tay"],["🙂‍↕️","head shaking vertically","đầu bắt tay"],
    ["😌","relieved face","nhẹ nhõm mặt"],["😔","pensive face","mặt"],["😪","sleepy face","mặt"],
    ["🤤","drooling face","mặt"],["😴","sleeping face","mặt"],
    ["😷","face with medical mask","mặt có y tế khẩu trang"],["🤒","face with thermometer","mặt có nhiệt kế"],
    ["🤕","face with head-bandage","mặt có đầu băng gạc"],["🤢","nauseated face","mặt"],
    ["🤮","face vomiting","mặt"],["🤧","sneezing face","mặt"],["🥵","hot face","nóng mặt"],["🥶","cold face","mặt"],
    ["🥴","woozy face","mặt"],["😵","face with crossed-out eyes","mặt có bắt chéo mắt"],
    ["😵‍💫","face with spiral eyes","mặt có xoắn ốc mắt"],["🤯","exploding head","đầu"],
    ["🤠","cowboy hat face","mũ mặt"],["🥳","partying face","mặt"],["🥸","disguised face","mặt"],
    ["😎","smiling face with sunglasses","cười mỉm mặt có kính râm"],["🤓","nerd face","mặt"],
    ["🧐","face with monocle","mặt có"],["😕","confused face","mặt"],
    ["🫤","face with diagonal mouth","mặt có miệng"],["😟","worried face","mặt"],
    ["🙁","slightly frowning face","hơi cau mày mặt"],["☹️","frowning face","cau mày mặt"],
    ["😮","face with open mouth","mặt có mở miệng"],["😯","hushed face","nín thở mặt"],
    ["😲","astonished face","kinh ngạc mặt"],["😳","flushed face","mặt"],["🥺","pleading face","mặt"],
    ["🥹","face holding back tears","mặt cầm nắm lùi nước mắt"],
    ["😦","frowning face with open mouth","cau mày mặt có mở miệng"],["😧","anguished face","mặt"],
    ["😨","fearful face","mặt"],["😰","anxious face with sweat","mặt có mồ hôi"],
    ["😥","sad but relieved face","nhẹ nhõm mặt"],["😢","crying face","khóc mặt"],
    ["😭","loudly crying face","khóc mặt"],["😱","face screaming in fear","mặt"],["😖","confounded face","mặt"],
    ["😣","persevering face","mặt"],["😞","disappointed face","mặt"],
    ["😓","downcast face with sweat","mặt có mồ hôi"],["😩","weary face","mệt mỏi mặt"],["😫","tired face","mặt"],
    ["🥱","yawning face","mặt"],["😤","face with steam from nose","mặt có mũi"],["😡","enraged face","mặt"],
    ["😠","angry face","tức giận mặt"],["🤬","face with symbols on mouth","mặt có ký hiệu bật miệng"],
    ["😈","smiling face with horns","cười mỉm mặt có sừng"],["👿","angry face with horns","tức giận mặt có sừng"],
    ["💀","skull","đầu lâu"],["☠️","skull and crossbones","đầu lâu"],["💩","pile of poo",""],
    ["🤡","clown face","mặt"],["👹","ogre",""],["👺","goblin",""],["👻","ghost",""],
    ["👽","alien","người ngoài hành tinh"],["👾","alien monster","người ngoài hành tinh"],["🤖","robot",""],
    ["😺","grinning cat","cười nhe răng mèo"],
    ["😸","grinning cat with smiling eyes","cười nhe răng mèo có mỉm mắt"],
    ["😹","cat with tears of joy","mèo có nước mắt vui sướng"],
    ["😻","smiling cat with heart-eyes","cười mỉm mèo có trái tim mắt"],["😼","cat with wry smile","mèo có"],
    ["😽","kissing cat","hôn mèo"],["🙀","weary cat","mệt mỏi mèo"],["😿","crying cat","khóc mèo"],
    ["😾","pouting cat","phụng phịu mèo"],["🙈","see-no-evil monkey","không quỷ dữ khỉ"],
    ["🙉","hear-no-evil monkey","không quỷ dữ khỉ"],["🙊","speak-no-evil monkey","không quỷ dữ khỉ"],
    ["💌","love letter","tình yêu"],["💘","heart with arrow","trái tim có mũi tên"],
    ["💝","heart with ribbon","trái tim có nơ ruy băng"],["💖","sparkling heart","trái tim"],
    ["💗","growing heart","trái tim"],["💓","beating heart","trái tim"],["💞","revolving hearts","trái tim"],
    ["💕","two hearts","hai trái tim"],["💟","heart decoration","trái tim trang trí"],
    ["❣️","heart exclamation","trái tim chấm than"],["💔","broken heart","trái tim"],
    ["❤️‍🔥","heart on fire","trái tim bật lửa"],["❤️‍🩹","mending heart","trái tim"],
    ["❤️","red heart","đỏ trái tim"],["🩷","pink heart","trái tim"],["🧡","orange heart","cam trái tim"],
    ["💛","yellow heart","vàng trái tim"],["💚","green heart","xanh lá trái tim"],
    ["💙","blue heart","xanh dương trái tim"],["🩵","light blue heart","nhạt sáng xanh dương trái tim"],
    ["💜","purple heart","tím trái tim"],["🤎","brown heart","nâu trái tim"],["🖤","black heart","đen trái tim"],
    ["🩶","grey heart","trái tim"],["🤍","white heart","trắng trái tim"],["💋","kiss mark","hôn dấu"],
    ["💯","hundred points",""],["💢","anger symbol","tức giận ký hiệu"],["💥","collision",""],["💫","dizzy",""],
    ["💦","sweat droplets","mồ hôi"],["💨","dashing away",""],["🕳️","hole","lỗ hổng"],
    ["💬","speech balloon","lời nói bóng bay"],["👁️‍🗨️","eye in speech bubble","mắt lời nói bong bóng"],
    ["🗨️","left speech bubble","trái lời nói bong bóng"],["🗯️","right anger bubble","phải tức giận bong bóng"],
    ["💭","thought balloon","bóng bay"],["💤","ZZZ",""]
  ]},
  { g: "Người & cơ thể", items: [
    ["👋","waving hand","bàn tay"],["🤚","raised back of hand","giơ lên lùi bàn tay"],
    ["🖐️","hand with fingers splayed","bàn tay có ngón"],["✋","raised hand","giơ lên bàn tay"],
    ["🖖","vulcan salute",""],["🫱","rightwards hand","sang phải bàn tay"],
    ["🫲","leftwards hand","sang trái bàn tay"],["🫳","palm down hand","lòng bàn tay xuống"],
    ["🫴","palm up hand","lòng bàn tay lên"],["🫷","leftwards pushing hand","sang trái đẩy bàn tay"],
    ["🫸","rightwards pushing hand","sang phải đẩy bàn tay"],["👌","OK hand","bàn tay"],
    ["🤌","pinched fingers","ngón tay"],["🤏","pinching hand","bàn tay"],["✌️","victory hand","bàn tay"],
    ["🤞","crossed fingers","bắt chéo ngón tay"],
    ["🫰","hand with index finger and thumb crossed","bàn tay có ngón trỏ bắt chéo"],
    ["🤟","love-you gesture","tình yêu"],["🤘","sign of the horns","biển báo sừng"],["🤙","call me hand","bàn tay"],
    ["👈","backhand index pointing left","mu bàn tay ngón trỏ chỉ trái"],
    ["👉","backhand index pointing right","mu bàn tay ngón trỏ chỉ phải"],
    ["👆","backhand index pointing up","mu bàn tay ngón trỏ chỉ lên"],["🖕","middle finger","ngón tay"],
    ["👇","backhand index pointing down","mu bàn tay ngón trỏ chỉ xuống"],
    ["☝️","index pointing up","ngón trỏ chỉ lên"],["🫵","index pointing at the viewer","ngón trỏ chỉ"],
    ["👍","thumbs up","ngón cái lên"],["👎","thumbs down","ngón cái xuống"],["✊","raised fist","giơ lên nắm đấm"],
    ["👊","oncoming fist","đang tới nắm đấm"],["🤛","left-facing fist","trái hướng nắm đấm"],
    ["🤜","right-facing fist","phải hướng nắm đấm"],["👏","clapping hands","bàn tay"],
    ["🙌","raising hands","giơ bàn tay"],["🫶","heart hands","trái tim bàn tay"],["👐","open hands","mở bàn tay"],
    ["🤲","palms up together","lên"],["🤝","handshake",""],["🙏","folded hands","bàn tay"],
    ["✍️","writing hand","bàn tay"],["💅","nail polish",""],["🤳","selfie",""],["💪","flexed biceps",""],
    ["🦾","mechanical arm","cơ khí"],["🦿","mechanical leg","cơ khí chân"],["🦵","leg","chân"],["🦶","foot",""],
    ["👂","ear","tai"],["🦻","ear with hearing aid","tai có"],["👃","nose","mũi"],["🧠","brain",""],
    ["🫀","anatomical heart","trái tim"],["🫁","lungs",""],["🦷","tooth",""],["🦴","bone","xương"],
    ["👀","eyes","mắt"],["👁️","eye","mắt"],["👅","tongue","lưỡi"],["👄","mouth","miệng"],["🫦","biting lip",""],
    ["👶","baby","em bé"],["🧒","child","trẻ em"],["👦","boy","bé trai"],["👧","girl","bé gái"],
    ["🧑","person","người"],["👱","person: blond hair","người tóc vàng"],["👨","man","đàn ông người nam"],
    ["🧔","person: beard","người râu"],["🧔‍♂️","man: beard","đàn ông người nam râu"],
    ["🧔‍♀️","woman: beard","phụ nữ đàn bà râu"],["👨‍🦰","man: red hair","đàn ông người nam đỏ tóc"],
    ["👨‍🦱","man: curly hair","đàn ông người nam xoăn tóc"],
    ["👨‍🦳","man: white hair","đàn ông người nam trắng tóc"],["👨‍🦲","man: bald","đàn ông người nam hói"],
    ["👩","woman","phụ nữ đàn bà"],["👩‍🦰","woman: red hair","phụ nữ đàn bà đỏ tóc"],
    ["🧑‍🦰","person: red hair","người đỏ tóc"],["👩‍🦱","woman: curly hair","phụ nữ đàn bà xoăn tóc"],
    ["🧑‍🦱","person: curly hair","người xoăn tóc"],["👩‍🦳","woman: white hair","phụ nữ đàn bà trắng tóc"],
    ["🧑‍🦳","person: white hair","người trắng tóc"],["👩‍🦲","woman: bald","phụ nữ đàn bà hói"],
    ["🧑‍🦲","person: bald","người hói"],["👱‍♀️","woman: blond hair","phụ nữ đàn bà tóc vàng"],
    ["👱‍♂️","man: blond hair","đàn ông người nam tóc vàng"],["🧓","older person","người"],
    ["👴","old man","già đàn ông người nam"],["👵","old woman","già phụ nữ đàn bà"],
    ["🙍","person frowning","người cau mày"],["🙍‍♂️","man frowning","đàn ông người nam cau mày"],
    ["🙍‍♀️","woman frowning","phụ nữ đàn bà cau mày"],["🙎","person pouting","người phụng phịu"],
    ["🙎‍♂️","man pouting","đàn ông người nam phụng phịu"],["🙎‍♀️","woman pouting","phụ nữ đàn bà phụng phịu"],
    ["🙅","person gesturing NO","người ra hiệu không"],
    ["🙅‍♂️","man gesturing NO","đàn ông người nam ra hiệu không"],
    ["🙅‍♀️","woman gesturing NO","phụ nữ đàn bà ra hiệu không"],["🙆","person gesturing OK","người ra hiệu"],
    ["🙆‍♂️","man gesturing OK","đàn ông người nam ra hiệu"],
    ["🙆‍♀️","woman gesturing OK","phụ nữ đàn bà ra hiệu"],["💁","person tipping hand","người nghiêng bàn tay"],
    ["💁‍♂️","man tipping hand","đàn ông người nam nghiêng bàn tay"],
    ["💁‍♀️","woman tipping hand","phụ nữ đàn bà nghiêng bàn tay"],
    ["🙋","person raising hand","người giơ bàn tay"],["🙋‍♂️","man raising hand","đàn ông người nam giơ bàn tay"],
    ["🙋‍♀️","woman raising hand","phụ nữ đàn bà giơ bàn tay"],["🧏","deaf person","khiếm thính người"],
    ["🧏‍♂️","deaf man","khiếm thính đàn ông người nam"],["🧏‍♀️","deaf woman","khiếm thính phụ nữ đàn bà"],
    ["🙇","person bowing","người cúi chào"],["🙇‍♂️","man bowing","đàn ông người nam cúi chào"],
    ["🙇‍♀️","woman bowing","phụ nữ đàn bà cúi chào"],["🤦","person facepalming","người ôm mặt"],
    ["🤦‍♂️","man facepalming","đàn ông người nam ôm mặt"],["🤦‍♀️","woman facepalming","phụ nữ đàn bà ôm mặt"],
    ["🤷","person shrugging","người nhún vai"],["🤷‍♂️","man shrugging","đàn ông người nam nhún vai"],
    ["🤷‍♀️","woman shrugging","phụ nữ đàn bà nhún vai"],["🧑‍⚕️","health worker","y tế bác sĩ công nhân"],
    ["👨‍⚕️","man health worker","đàn ông người nam y tế bác sĩ công nhân"],
    ["👩‍⚕️","woman health worker","phụ nữ đàn bà y tế bác sĩ công nhân"],["🧑‍🎓","student","học sinh viên"],
    ["👨‍🎓","man student","đàn ông người nam học sinh viên"],
    ["👩‍🎓","woman student","phụ nữ đàn bà học sinh viên"],["🧑‍🏫","teacher","giáo viên"],
    ["👨‍🏫","man teacher","đàn ông người nam giáo viên"],["👩‍🏫","woman teacher","phụ nữ đàn bà giáo viên"],
    ["🧑‍⚖️","judge","thẩm phán"],["👨‍⚖️","man judge","đàn ông người nam thẩm phán"],
    ["👩‍⚖️","woman judge","phụ nữ đàn bà thẩm phán"],["🧑‍🌾","farmer","nông dân"],
    ["👨‍🌾","man farmer","đàn ông người nam nông dân"],["👩‍🌾","woman farmer","phụ nữ đàn bà nông dân"],
    ["🧑‍🍳","cook","đầu bếp"],["👨‍🍳","man cook","đàn ông người nam đầu bếp"],
    ["👩‍🍳","woman cook","phụ nữ đàn bà đầu bếp"],["🧑‍🔧","mechanic","thợ máy"],
    ["👨‍🔧","man mechanic","đàn ông người nam thợ máy"],["👩‍🔧","woman mechanic","phụ nữ đàn bà thợ máy"],
    ["🧑‍🏭","factory worker","nhà máy công nhân"],
    ["👨‍🏭","man factory worker","đàn ông người nam nhà máy công nhân"],
    ["👩‍🏭","woman factory worker","phụ nữ đàn bà nhà máy công nhân"],
    ["🧑‍💼","office worker","văn phòng công nhân"],
    ["👨‍💼","man office worker","đàn ông người nam văn phòng công nhân"],
    ["👩‍💼","woman office worker","phụ nữ đàn bà văn phòng công nhân"],["🧑‍🔬","scientist","nhà khoa học"],
    ["👨‍🔬","man scientist","đàn ông người nam nhà khoa học"],
    ["👩‍🔬","woman scientist","phụ nữ đàn bà nhà khoa học"],["🧑‍💻","technologist","kỹ thuật viên"],
    ["👨‍💻","man technologist","đàn ông người nam kỹ thuật viên"],
    ["👩‍💻","woman technologist","phụ nữ đàn bà kỹ thuật viên"],["🧑‍🎤","singer","ca sĩ"],
    ["👨‍🎤","man singer","đàn ông người nam ca sĩ"],["👩‍🎤","woman singer","phụ nữ đàn bà ca sĩ"],
    ["🧑‍🎨","artist","hoạ sĩ"],["👨‍🎨","man artist","đàn ông người nam hoạ sĩ"],
    ["👩‍🎨","woman artist","phụ nữ đàn bà hoạ sĩ"],["🧑‍✈️","pilot","phi công"],
    ["👨‍✈️","man pilot","đàn ông người nam phi công"],["👩‍✈️","woman pilot","phụ nữ đàn bà phi công"],
    ["🧑‍🚀","astronaut","phi hành gia"],["👨‍🚀","man astronaut","đàn ông người nam phi hành gia"],
    ["👩‍🚀","woman astronaut","phụ nữ đàn bà phi hành gia"],["🧑‍🚒","firefighter","lính cứu hoả"],
    ["👨‍🚒","man firefighter","đàn ông người nam lính cứu hoả"],
    ["👩‍🚒","woman firefighter","phụ nữ đàn bà lính cứu hoả"],["👮","police officer","cảnh sát sĩ quan"],
    ["👮‍♂️","man police officer","đàn ông người nam cảnh sát sĩ quan"],
    ["👮‍♀️","woman police officer","phụ nữ đàn bà cảnh sát sĩ quan"],["🕵️","detective","thám tử"],
    ["🕵️‍♂️","man detective","đàn ông người nam thám tử"],["🕵️‍♀️","woman detective","phụ nữ đàn bà thám tử"],
    ["💂","guard","lính gác"],["💂‍♂️","man guard","đàn ông người nam lính gác"],
    ["💂‍♀️","woman guard","phụ nữ đàn bà lính gác"],["🥷","ninja",""],
    ["👷","construction worker","xây dựng công nhân"],
    ["👷‍♂️","man construction worker","đàn ông người nam xây dựng công nhân"],
    ["👷‍♀️","woman construction worker","phụ nữ đàn bà xây dựng công nhân"],
    ["🫅","person with crown","người có vương miện"],["🤴","prince",""],["👸","princess",""],
    ["👳","person wearing turban","người đeo khăn xếp"],
    ["👳‍♂️","man wearing turban","đàn ông người nam đeo khăn xếp"],
    ["👳‍♀️","woman wearing turban","phụ nữ đàn bà đeo khăn xếp"],["👲","person with skullcap","người có"],
    ["🧕","woman with headscarf","phụ nữ đàn bà có"],["🤵","person in tuxedo","người lễ phục"],
    ["🤵‍♂️","man in tuxedo","đàn ông người nam lễ phục"],["🤵‍♀️","woman in tuxedo","phụ nữ đàn bà lễ phục"],
    ["👰","person with veil","người có khăn voan"],["👰‍♂️","man with veil","đàn ông người nam có khăn voan"],
    ["👰‍♀️","woman with veil","phụ nữ đàn bà có khăn voan"],["🤰","pregnant woman","mang thai phụ nữ đàn bà"],
    ["🫃","pregnant man","mang thai đàn ông người nam"],["🫄","pregnant person","mang thai người"],
    ["🤱","breast-feeding","cho ăn"],["👩‍🍼","woman feeding baby","phụ nữ đàn bà cho ăn em bé"],
    ["👨‍🍼","man feeding baby","đàn ông người nam cho ăn em bé"],
    ["🧑‍🍼","person feeding baby","người cho ăn em bé"],["👼","baby angel","em bé"],
    ["🎅","Santa Claus","ông già noel"],["🤶","Mrs. Claus","ông già noel"],["🧑‍🎄","mx claus","ông già noel"],
    ["🦸","superhero","siêu anh hùng"],["🦸‍♂️","man superhero","đàn ông người nam siêu anh hùng"],
    ["🦸‍♀️","woman superhero","phụ nữ đàn bà siêu anh hùng"],["🦹","supervillain","ác nhân"],
    ["🦹‍♂️","man supervillain","đàn ông người nam ác nhân"],
    ["🦹‍♀️","woman supervillain","phụ nữ đàn bà ác nhân"],["🧙","mage","pháp sư"],
    ["🧙‍♂️","man mage","đàn ông người nam pháp sư"],["🧙‍♀️","woman mage","phụ nữ đàn bà pháp sư"],
    ["🧚","fairy","tiên"],["🧚‍♂️","man fairy","đàn ông người nam tiên"],
    ["🧚‍♀️","woman fairy","phụ nữ đàn bà tiên"],["🧛","vampire","ma cà rồng"],
    ["🧛‍♂️","man vampire","đàn ông người nam ma cà rồng"],["🧛‍♀️","woman vampire","phụ nữ đàn bà ma cà rồng"],
    ["🧜","merperson",""],["🧜‍♂️","merman",""],["🧜‍♀️","mermaid",""],["🧝","elf","yêu tinh"],
    ["🧝‍♂️","man elf","đàn ông người nam yêu tinh"],["🧝‍♀️","woman elf","phụ nữ đàn bà yêu tinh"],
    ["🧞","genie","thần đèn"],["🧞‍♂️","man genie","đàn ông người nam thần đèn"],
    ["🧞‍♀️","woman genie","phụ nữ đàn bà thần đèn"],["🧟","zombie","xác sống"],
    ["🧟‍♂️","man zombie","đàn ông người nam xác sống"],["🧟‍♀️","woman zombie","phụ nữ đàn bà xác sống"],
    ["🧌","troll",""],["💆","person getting massage","người đang mát xa"],
    ["💆‍♂️","man getting massage","đàn ông người nam đang mát xa"],
    ["💆‍♀️","woman getting massage","phụ nữ đàn bà đang mát xa"],
    ["💇","person getting haircut","người đang cắt tóc"],
    ["💇‍♂️","man getting haircut","đàn ông người nam đang cắt tóc"],
    ["💇‍♀️","woman getting haircut","phụ nữ đàn bà đang cắt tóc"],["🚶","person walking","người đi bộ"],
    ["🚶‍♂️","man walking","đàn ông người nam đi bộ"],["🚶‍♀️","woman walking","phụ nữ đàn bà đi bộ"],
    ["🚶‍➡️","person walking facing right","người đi bộ hướng phải"],
    ["🚶‍♀️‍➡️","woman walking facing right","phụ nữ đàn bà đi bộ hướng phải"],
    ["🚶‍♂️‍➡️","man walking facing right","đàn ông người nam đi bộ hướng phải"],
    ["🧍","person standing","người đứng"],["🧍‍♂️","man standing","đàn ông người nam đứng"],
    ["🧍‍♀️","woman standing","phụ nữ đàn bà đứng"],["🧎","person kneeling","người quỳ"],
    ["🧎‍♂️","man kneeling","đàn ông người nam quỳ"],["🧎‍♀️","woman kneeling","phụ nữ đàn bà quỳ"],
    ["🧎‍➡️","person kneeling facing right","người quỳ hướng phải"],
    ["🧎‍♀️‍➡️","woman kneeling facing right","phụ nữ đàn bà quỳ hướng phải"],
    ["🧎‍♂️‍➡️","man kneeling facing right","đàn ông người nam quỳ hướng phải"],
    ["🧑‍🦯","person with white cane","người có trắng gậy"],
    ["🧑‍🦯‍➡️","person with white cane facing right","người có trắng gậy hướng phải"],
    ["👨‍🦯","man with white cane","đàn ông người nam có trắng gậy"],
    ["👨‍🦯‍➡️","man with white cane facing right","đàn ông người nam có trắng gậy hướng phải"],
    ["👩‍🦯","woman with white cane","phụ nữ đàn bà có trắng gậy"],
    ["👩‍🦯‍➡️","woman with white cane facing right","phụ nữ đàn bà có trắng gậy hướng phải"],
    ["🧑‍🦼","person in motorized wheelchair","người chạy máy xe lăn"],
    ["🧑‍🦼‍➡️","person in motorized wheelchair facing right","người chạy máy xe lăn hướng phải"],
    ["👨‍🦼","man in motorized wheelchair","đàn ông người nam chạy máy xe lăn"],
    ["👨‍🦼‍➡️","man in motorized wheelchair facing right","đàn ông người nam chạy máy xe lăn hướng phải"],
    ["👩‍🦼","woman in motorized wheelchair","phụ nữ đàn bà chạy máy xe lăn"],
    ["👩‍🦼‍➡️","woman in motorized wheelchair facing right","phụ nữ đàn bà chạy máy xe lăn hướng phải"],
    ["🧑‍🦽","person in manual wheelchair","người thủ công xe lăn"],
    ["🧑‍🦽‍➡️","person in manual wheelchair facing right","người thủ công xe lăn hướng phải"],
    ["👨‍🦽","man in manual wheelchair","đàn ông người nam thủ công xe lăn"],
    ["👨‍🦽‍➡️","man in manual wheelchair facing right","đàn ông người nam thủ công xe lăn hướng phải"],
    ["👩‍🦽","woman in manual wheelchair","phụ nữ đàn bà thủ công xe lăn"],
    ["👩‍🦽‍➡️","woman in manual wheelchair facing right","phụ nữ đàn bà thủ công xe lăn hướng phải"],
    ["🏃","person running","người chạy"],["🏃‍♂️","man running","đàn ông người nam chạy"],
    ["🏃‍♀️","woman running","phụ nữ đàn bà chạy"],["🏃‍➡️","person running facing right","người chạy hướng phải"],
    ["🏃‍♀️‍➡️","woman running facing right","phụ nữ đàn bà chạy hướng phải"],
    ["🏃‍♂️‍➡️","man running facing right","đàn ông người nam chạy hướng phải"],
    ["💃","woman dancing","phụ nữ đàn bà nhảy múa"],["🕺","man dancing","đàn ông người nam nhảy múa"],
    ["🕴️","person in suit levitating","người bộ vest"],["👯","people with bunny ears","người có thỏ tai"],
    ["👯‍♂️","men with bunny ears","đàn ông có thỏ tai"],["👯‍♀️","women with bunny ears","phụ nữ có thỏ tai"],
    ["🧖","person in steamy room","người xông hơi phòng"],
    ["🧖‍♂️","man in steamy room","đàn ông người nam xông hơi phòng"],
    ["🧖‍♀️","woman in steamy room","phụ nữ đàn bà xông hơi phòng"],["🧗","person climbing","người leo núi"],
    ["🧗‍♂️","man climbing","đàn ông người nam leo núi"],["🧗‍♀️","woman climbing","phụ nữ đàn bà leo núi"],
    ["🤺","person fencing","người"],["🏇","horse racing","ngựa đua"],["⛷️","skier",""],["🏂","snowboarder",""],
    ["🏌️","person golfing","người đánh golf"],["🏌️‍♂️","man golfing","đàn ông người nam đánh golf"],
    ["🏌️‍♀️","woman golfing","phụ nữ đàn bà đánh golf"],["🏄","person surfing","người lướt sóng"],
    ["🏄‍♂️","man surfing","đàn ông người nam lướt sóng"],["🏄‍♀️","woman surfing","phụ nữ đàn bà lướt sóng"],
    ["🚣","person rowing boat","người chèo thuyền"],["🚣‍♂️","man rowing boat","đàn ông người nam chèo thuyền"],
    ["🚣‍♀️","woman rowing boat","phụ nữ đàn bà chèo thuyền"],["🏊","person swimming","người bơi"],
    ["🏊‍♂️","man swimming","đàn ông người nam bơi"],["🏊‍♀️","woman swimming","phụ nữ đàn bà bơi"],
    ["⛹️","person bouncing ball","người nảy bóng"],["⛹️‍♂️","man bouncing ball","đàn ông người nam nảy bóng"],
    ["⛹️‍♀️","woman bouncing ball","phụ nữ đàn bà nảy bóng"],["🏋️","person lifting weights","người nâng tạ"],
    ["🏋️‍♂️","man lifting weights","đàn ông người nam nâng tạ"],
    ["🏋️‍♀️","woman lifting weights","phụ nữ đàn bà nâng tạ"],["🚴","person biking","người đạp xe"],
    ["🚴‍♂️","man biking","đàn ông người nam đạp xe"],["🚴‍♀️","woman biking","phụ nữ đàn bà đạp xe"],
    ["🚵","person mountain biking","người núi đạp xe"],
    ["🚵‍♂️","man mountain biking","đàn ông người nam núi đạp xe"],
    ["🚵‍♀️","woman mountain biking","phụ nữ đàn bà núi đạp xe"],["🤸","person cartwheeling","người lộn nhào"],
    ["🤸‍♂️","man cartwheeling","đàn ông người nam lộn nhào"],
    ["🤸‍♀️","woman cartwheeling","phụ nữ đàn bà lộn nhào"],["🤼","people wrestling","người đấu vật"],
    ["🤼‍♂️","men wrestling","đàn ông đấu vật"],["🤼‍♀️","women wrestling","phụ nữ đấu vật"],
    ["🤽","person playing water polo","người chơi nước bóng"],
    ["🤽‍♂️","man playing water polo","đàn ông người nam chơi nước bóng"],
    ["🤽‍♀️","woman playing water polo","phụ nữ đàn bà chơi nước bóng"],
    ["🤾","person playing handball","người chơi bóng ném"],
    ["🤾‍♂️","man playing handball","đàn ông người nam chơi bóng ném"],
    ["🤾‍♀️","woman playing handball","phụ nữ đàn bà chơi bóng ném"],["🤹","person juggling","người tung hứng"],
    ["🤹‍♂️","man juggling","đàn ông người nam tung hứng"],["🤹‍♀️","woman juggling","phụ nữ đàn bà tung hứng"],
    ["🧘","person in lotus position","người hoa sen tư thế"],
    ["🧘‍♂️","man in lotus position","đàn ông người nam hoa sen tư thế"],
    ["🧘‍♀️","woman in lotus position","phụ nữ đàn bà hoa sen tư thế"],["🛀","person taking bath","người"],
    ["🛌","person in bed","người giường"],["🧑‍🤝‍🧑","people holding hands","người cầm nắm bàn tay"],
    ["👭","women holding hands","phụ nữ cầm nắm bàn tay"],
    ["👫","woman and man holding hands","phụ nữ đàn bà ông người nam cầm nắm bàn tay"],
    ["👬","men holding hands","đàn ông cầm nắm bàn tay"],["💏","kiss","hôn"],
    ["👩‍❤️‍💋‍👨","kiss: woman, man","hôn phụ nữ đàn bà ông người nam"],
    ["👨‍❤️‍💋‍👨","kiss: man, man","hôn đàn ông người nam"],["👩‍❤️‍💋‍👩","kiss: woman, woman","hôn phụ nữ đàn bà"],
    ["💑","couple with heart","cặp đôi có trái tim"],
    ["👩‍❤️‍👨","couple with heart: woman, man","cặp đôi có trái tim phụ nữ đàn bà ông người nam"],
    ["👨‍❤️‍👨","couple with heart: man, man","cặp đôi có trái tim đàn ông người nam"],
    ["👩‍❤️‍👩","couple with heart: woman, woman","cặp đôi có trái tim phụ nữ đàn bà"],
    ["👨‍👩‍👦","family: man, woman, boy","gia đình đàn ông người nam phụ nữ bà bé trai"],
    ["👨‍👩‍👧","family: man, woman, girl","gia đình đàn ông người nam phụ nữ bà bé gái"],
    ["👨‍👩‍👧‍👦","family: man, woman, girl, boy","gia đình đàn ông người nam phụ nữ bà bé gái trai"],
    ["👨‍👩‍👦‍👦","family: man, woman, boy, boy","gia đình đàn ông người nam phụ nữ bà bé trai"],
    ["👨‍👩‍👧‍👧","family: man, woman, girl, girl","gia đình đàn ông người nam phụ nữ bà bé gái"],
    ["👨‍👨‍👦","family: man, man, boy","gia đình đàn ông người nam bé trai"],
    ["👨‍👨‍👧","family: man, man, girl","gia đình đàn ông người nam bé gái"],
    ["👨‍👨‍👧‍👦","family: man, man, girl, boy","gia đình đàn ông người nam bé gái trai"],
    ["👨‍👨‍👦‍👦","family: man, man, boy, boy","gia đình đàn ông người nam bé trai"],
    ["👨‍👨‍👧‍👧","family: man, man, girl, girl","gia đình đàn ông người nam bé gái"],
    ["👩‍👩‍👦","family: woman, woman, boy","gia đình phụ nữ đàn bà bé trai"],
    ["👩‍👩‍👧","family: woman, woman, girl","gia đình phụ nữ đàn bà bé gái"],
    ["👩‍👩‍👧‍👦","family: woman, woman, girl, boy","gia đình phụ nữ đàn bà bé gái trai"],
    ["👩‍👩‍👦‍👦","family: woman, woman, boy, boy","gia đình phụ nữ đàn bà bé trai"],
    ["👩‍👩‍👧‍👧","family: woman, woman, girl, girl","gia đình phụ nữ đàn bà bé gái"],
    ["👨‍👦","family: man, boy","gia đình đàn ông người nam bé trai"],
    ["👨‍👦‍👦","family: man, boy, boy","gia đình đàn ông người nam bé trai"],
    ["👨‍👧","family: man, girl","gia đình đàn ông người nam bé gái"],
    ["👨‍👧‍👦","family: man, girl, boy","gia đình đàn ông người nam bé gái trai"],
    ["👨‍👧‍👧","family: man, girl, girl","gia đình đàn ông người nam bé gái"],
    ["👩‍👦","family: woman, boy","gia đình phụ nữ đàn bà bé trai"],
    ["👩‍👦‍👦","family: woman, boy, boy","gia đình phụ nữ đàn bà bé trai"],
    ["👩‍👧","family: woman, girl","gia đình phụ nữ đàn bà bé gái"],
    ["👩‍👧‍👦","family: woman, girl, boy","gia đình phụ nữ đàn bà bé gái trai"],
    ["👩‍👧‍👧","family: woman, girl, girl","gia đình phụ nữ đàn bà bé gái"],["🗣️","speaking head","đầu"],
    ["👤","bust in silhouette",""],["👥","busts in silhouette",""],["🫂","people hugging","người"],
    ["👪","family","gia đình"],["🧑‍🧑‍🧒","family: adult, adult, child","gia đình người lớn trẻ em"],
    ["🧑‍🧑‍🧒‍🧒","family: adult, adult, child, child","gia đình người lớn trẻ em"],
    ["🧑‍🧒","family: adult, child","gia đình người lớn trẻ em"],
    ["🧑‍🧒‍🧒","family: adult, child, child","gia đình người lớn trẻ em"],["👣","footprints",""]
  ]},
  { g: "Động vật & thiên nhiên", items: [
    ["🐵","monkey face","khỉ mặt"],["🐒","monkey","khỉ"],["🦍","gorilla",""],["🦧","orangutan",""],
    ["🐶","dog face","chó mặt"],["🐕","dog","chó"],["🦮","guide dog","chó"],["🐕‍🦺","service dog","dịch vụ chó"],
    ["🐩","poodle",""],["🐺","wolf",""],["🦊","fox",""],["🦝","raccoon",""],["🐱","cat face","mèo mặt"],
    ["🐈","cat","mèo"],["🐈‍⬛","black cat","đen mèo"],["🦁","lion",""],["🐯","tiger face","hổ mặt"],
    ["🐅","tiger","hổ"],["🐆","leopard",""],["🐴","horse face","ngựa mặt"],["🫎","moose",""],["🫏","donkey",""],
    ["🐎","horse","ngựa"],["🦄","unicorn",""],["🦓","zebra",""],["🦌","deer",""],["🦬","bison",""],
    ["🐮","cow face","bò mặt"],["🐂","ox",""],["🐃","water buffalo","nước"],["🐄","cow","bò"],
    ["🐷","pig face","lợn heo mặt"],["🐖","pig","lợn heo"],["🐗","boar",""],["🐽","pig nose","lợn heo mũi"],
    ["🐏","ram",""],["🐑","ewe",""],["🐐","goat",""],["🐪","camel","lạc đà"],["🐫","two-hump camel","hai lạc đà"],
    ["🦙","llama",""],["🦒","giraffe",""],["🐘","elephant",""],["🦣","mammoth",""],["🦏","rhinoceros",""],
    ["🦛","hippopotamus",""],["🐭","mouse face","chuột mặt"],["🐁","mouse","chuột"],["🐀","rat",""],
    ["🐹","hamster",""],["🐰","rabbit face","thỏ mặt"],["🐇","rabbit","thỏ"],["🐿️","chipmunk",""],["🦫","beaver",""],
    ["🦔","hedgehog",""],["🦇","bat",""],["🐻","bear","gấu"],["🐻‍❄️","polar bear","gấu"],["🐨","koala",""],
    ["🐼","panda",""],["🦥","sloth",""],["🦦","otter",""],["🦨","skunk",""],["🦘","kangaroo",""],["🦡","badger",""],
    ["🐾","paw prints",""],["🦃","turkey",""],["🐔","chicken",""],["🐓","rooster",""],
    ["🐣","hatching chick","gà con"],["🐤","baby chick","em bé gà con"],
    ["🐥","front-facing baby chick","hướng em bé gà con"],["🐦","bird","chim"],["🐧","penguin",""],["🕊️","dove",""],
    ["🦅","eagle",""],["🦆","duck",""],["🦢","swan",""],["🦉","owl",""],["🦤","dodo",""],["🪶","feather",""],
    ["🦩","flamingo",""],["🦚","peacock",""],["🦜","parrot",""],["🪽","wing",""],["🐦‍⬛","black bird","đen chim"],
    ["🪿","goose",""],["🐦‍🔥","phoenix",""],["🐸","frog",""],["🐊","crocodile",""],["🐢","turtle",""],
    ["🦎","lizard",""],["🐍","snake",""],["🐲","dragon face","rồng mặt"],["🐉","dragon","rồng"],["🦕","sauropod",""],
    ["🦖","T-Rex",""],["🐳","spouting whale","cá voi"],["🐋","whale","cá voi"],["🐬","dolphin",""],["🦭","seal",""],
    ["🐟","fish","cá"],["🐠","tropical fish","nhiệt đới cá"],["🐡","blowfish",""],["🦈","shark",""],
    ["🐙","octopus",""],["🐚","spiral shell","xoắn ốc"],["🪸","coral",""],["🪼","jellyfish",""],["🐌","snail",""],
    ["🦋","butterfly",""],["🐛","bug",""],["🐜","ant",""],["🐝","honeybee",""],["🪲","beetle","bọ cánh cứng"],
    ["🐞","lady beetle","bọ cánh cứng"],["🦗","cricket","dế"],["🪳","cockroach",""],["🕷️","spider","nhện"],
    ["🕸️","spider web","nhện"],["🦂","scorpion",""],["🦟","mosquito",""],["🪰","fly",""],["🪱","worm",""],
    ["🦠","microbe",""],["💐","bouquet",""],["🌸","cherry blossom","hoa nở"],["💮","white flower","trắng hoa"],
    ["🪷","lotus","hoa sen"],["🏵️","rosette",""],["🌹","rose",""],["🥀","wilted flower","hoa"],["🌺","hibiscus",""],
    ["🌻","sunflower",""],["🌼","blossom","hoa nở"],["🌷","tulip",""],["🪻","hyacinth",""],["🌱","seedling",""],
    ["🪴","potted plant",""],["🌲","evergreen tree","cây"],["🌳","deciduous tree","cây"],
    ["🌴","palm tree","lòng bàn tay cây"],["🌵","cactus",""],["🌾","sheaf of rice","cơm gạo"],["🌿","herb",""],
    ["☘️","shamrock",""],["🍀","four leaf clover","bốn lá"],["🍁","maple leaf","lá"],["🍂","fallen leaf","lá"],
    ["🍃","leaf fluttering in wind","lá gió"],["🪹","empty nest","tổ chim"],["🪺","nest with eggs","tổ chim có"],
    ["🍄","mushroom","nấm"]
  ]},
  { g: "Đồ ăn & thức uống", items: [
    ["🍇","grapes",""],["🍈","melon",""],["🍉","watermelon",""],["🍊","tangerine",""],["🍋","lemon",""],
    ["🍋‍🟩","lime",""],["🍌","banana",""],["🍍","pineapple",""],["🥭","mango",""],["🍎","red apple","đỏ táo"],
    ["🍏","green apple","xanh lá táo"],["🍐","pear",""],["🍑","peach",""],["🍒","cherries",""],["🍓","strawberry",""],
    ["🫐","blueberries",""],["🥝","kiwi fruit",""],["🍅","tomato",""],["🫒","olive",""],["🥥","coconut",""],
    ["🥑","avocado",""],["🍆","eggplant",""],["🥔","potato","khoai tây"],["🥕","carrot",""],
    ["🌽","ear of corn","tai"],["🌶️","hot pepper","nóng ớt"],["🫑","bell pepper","chuông ớt"],["🥒","cucumber",""],
    ["🥬","leafy green","xanh lá"],["🥦","broccoli",""],["🧄","garlic",""],["🧅","onion",""],["🥜","peanuts",""],
    ["🫘","beans",""],["🌰","chestnut",""],["🫚","ginger root",""],["🫛","pea pod",""],
    ["🍄‍🟫","brown mushroom","nâu nấm"],["🍞","bread","bánh mì"],["🥐","croissant",""],
    ["🥖","baguette bread","bánh mì"],["🫓","flatbread","bánh mì dẹt"],["🥨","pretzel",""],["🥯","bagel",""],
    ["🥞","pancakes",""],["🧇","waffle",""],["🧀","cheese wedge",""],["🍖","meat on bone","thịt bật xương"],
    ["🍗","poultry leg","chân"],["🥩","cut of meat","thịt"],["🥓","bacon",""],["🍔","hamburger",""],
    ["🍟","french fries",""],["🍕","pizza",""],["🌭","hot dog","nóng chó"],["🥪","sandwich",""],["🌮","taco",""],
    ["🌯","burrito",""],["🫔","tamale",""],["🥙","stuffed flatbread","bánh mì dẹt"],["🧆","falafel",""],
    ["🥚","egg",""],["🍳","cooking",""],["🥘","shallow pan of food","đồ ăn"],["🍲","pot of food","nồi đồ ăn"],
    ["🫕","fondue",""],["🥣","bowl with spoon","bát tô có thìa muỗng"],["🥗","green salad","xanh lá"],
    ["🍿","popcorn",""],["🧈","butter",""],["🧂","salt",""],["🥫","canned food","đồ ăn"],["🍱","bento box","hộp"],
    ["🍘","rice cracker","cơm gạo"],["🍙","rice ball","cơm gạo bóng"],["🍚","cooked rice","cơm gạo"],
    ["🍛","curry rice","cơm gạo"],["🍜","steaming bowl","bát tô"],["🍝","spaghetti",""],
    ["🍠","roasted sweet potato","khoai tây"],["🍢","oden",""],["🍣","sushi",""],["🍤","fried shrimp","tôm"],
    ["🍥","fish cake with swirl","cá bánh ngọt có"],["🥮","moon cake","mặt trăng bánh ngọt"],["🍡","dango",""],
    ["🥟","dumpling",""],["🥠","fortune cookie","bánh quy"],["🥡","takeout box","hộp"],["🦀","crab",""],
    ["🦞","lobster",""],["🦐","shrimp","tôm"],["🦑","squid",""],["🦪","oyster",""],
    ["🍦","soft ice cream","đá lạnh kem"],["🍧","shaved ice","đá lạnh"],["🍨","ice cream","đá lạnh kem"],
    ["🍩","doughnut",""],["🍪","cookie","bánh quy"],["🎂","birthday cake","bánh ngọt"],["🍰","shortcake",""],
    ["🧁","cupcake",""],["🥧","pie",""],["🍫","chocolate bar","thanh"],["🍬","candy",""],["🍭","lollipop",""],
    ["🍮","custard",""],["🍯","honey pot","nồi"],["🍼","baby bottle","em bé chai"],["🥛","glass of milk","ly cốc"],
    ["☕","hot beverage","nóng đồ uống"],["🫖","teapot",""],["🍵","teacup without handle","không có"],
    ["🍶","sake",""],["🍾","bottle with popping cork","chai có"],["🍷","wine glass","ly cốc"],
    ["🍸","cocktail glass","ly cốc"],["🍹","tropical drink","nhiệt đới"],["🍺","beer mug","bia"],
    ["🍻","clinking beer mugs","cụng ly bia"],["🥂","clinking glasses","cụng ly cốc"],
    ["🥃","tumbler glass","ly cốc"],["🫗","pouring liquid",""],["🥤","cup with straw","có"],
    ["🧋","bubble tea","bong bóng"],["🧃","beverage box","đồ uống hộp"],["🧉","mate",""],["🧊","ice","đá lạnh"],
    ["🥢","chopsticks",""],["🍽️","fork and knife with plate","nĩa dao có"],["🍴","fork and knife","nĩa dao"],
    ["🥄","spoon","thìa muỗng"],["🔪","kitchen knife","dao"],["🫙","jar",""],["🏺","amphora",""]
  ]},
  { g: "Du lịch & địa điểm", items: [
    ["🌍","globe showing Europe-Africa","quả địa cầu"],["🌎","globe showing Americas","quả địa cầu"],
    ["🌏","globe showing Asia-Australia","quả địa cầu"],["🌐","globe with meridians","quả địa cầu có"],
    ["🗺️","world map","bản đồ"],["🗾","map of Japan","bản đồ"],["🧭","compass",""],
    ["🏔️","snow-capped mountain","tuyết núi"],["⛰️","mountain","núi"],["🌋","volcano",""],["🗻","mount fuji",""],
    ["🏕️","camping",""],["🏖️","beach with umbrella","có ô dù"],["🏜️","desert","sa mạc"],
    ["🏝️","desert island","sa mạc"],["🏞️","national park",""],["🏟️","stadium",""],
    ["🏛️","classical building","toà nhà"],["🏗️","building construction","toà nhà xây dựng"],["🧱","brick",""],
    ["🪨","rock",""],["🪵","wood",""],["🛖","hut",""],["🏘️","houses",""],["🏚️","derelict house","nhà"],
    ["🏠","house","nhà"],["🏡","house with garden","nhà có"],["🏢","office building","văn phòng toà nhà"],
    ["🏣","Japanese post office","nhật bản bưu điện văn phòng"],["🏤","post office","bưu điện văn phòng"],
    ["🏥","hospital",""],["🏦","bank",""],["🏨","hotel","khách sạn"],["🏩","love hotel","tình yêu khách sạn"],
    ["🏪","convenience store","cửa hàng"],["🏫","school",""],["🏬","department store","cửa hàng"],
    ["🏭","factory","nhà máy"],["🏯","Japanese castle","nhật bản lâu đài"],["🏰","castle","lâu đài"],
    ["💒","wedding",""],["🗼","Tokyo tower",""],["🗽","Statue of Liberty",""],["⛪","church",""],["🕌","mosque",""],
    ["🛕","hindu temple",""],["🕍","synagogue",""],["⛩️","shinto shrine",""],["🕋","kaaba",""],
    ["⛲","fountain","đài phun nước"],["⛺","tent","lều"],["🌁","foggy",""],["🌃","night with stars","đêm có"],
    ["🏙️","cityscape","thành phố"],["🌄","sunrise over mountains","bình minh trên"],["🌅","sunrise","bình minh"],
    ["🌆","cityscape at dusk","thành phố"],["🌇","sunset",""],["🌉","bridge at night","đêm"],
    ["♨️","hot springs","nóng"],["🎠","carousel horse","ngựa"],["🛝","playground slide",""],
    ["🎡","ferris wheel","bánh xe"],["🎢","roller coaster","con lăn"],["💈","barber pole","cột"],
    ["🎪","circus tent","lều"],["🚂","locomotive",""],["🚃","railway car","đường sắt ô tô xe hơi"],
    ["🚄","high-speed train","cao tàu hoả"],["🚅","bullet train","tàu hoả"],["🚆","train","tàu hoả"],
    ["🚇","metro",""],["🚈","light rail","nhạt sáng"],["🚉","station",""],["🚊","tram","tàu điện"],
    ["🚝","monorail",""],["🚞","mountain railway","núi đường sắt"],["🚋","tram car","tàu điện ô tô xe hơi"],
    ["🚌","bus","xe buýt"],["🚍","oncoming bus","đang tới xe buýt"],["🚎","trolleybus",""],["🚐","minibus",""],
    ["🚑","ambulance",""],["🚒","fire engine","lửa"],["🚓","police car","cảnh sát ô tô xe hơi"],
    ["🚔","oncoming police car","đang tới cảnh sát ô tô xe hơi"],["🚕","taxi","taxi"],
    ["🚖","oncoming taxi","đang tới taxi"],["🚗","automobile","ô tô"],["🚘","oncoming automobile","đang tới ô tô"],
    ["🚙","sport utility vehicle",""],["🛻","pickup truck","xe tải"],["🚚","delivery truck","xe tải"],
    ["🚛","articulated lorry",""],["🚜","tractor",""],["🏎️","racing car","đua ô tô xe hơi"],["🏍️","motorcycle",""],
    ["🛵","motor scooter","động cơ xe tay ga"],["🦽","manual wheelchair","thủ công xe lăn"],
    ["🦼","motorized wheelchair","chạy máy xe lăn"],["🛺","auto rickshaw",""],["🚲","bicycle",""],
    ["🛴","kick scooter","xe tay ga"],["🛹","skateboard",""],["🛼","roller skate","con lăn trượt"],
    ["🚏","bus stop","xe buýt dừng"],["🛣️","motorway",""],["🛤️","railway track","đường sắt ray"],
    ["🛢️","oil drum","trống"],["⛽","fuel pump",""],["🛞","wheel","bánh xe"],
    ["🚨","police car light","cảnh sát ô tô xe hơi nhạt sáng"],
    ["🚥","horizontal traffic light","giao thông nhạt sáng"],
    ["🚦","vertical traffic light","dọc giao thông nhạt sáng"],["🛑","stop sign","dừng biển báo"],
    ["🚧","construction","xây dựng"],["⚓","anchor",""],["🛟","ring buoy","nhẫn"],["⛵","sailboat",""],
    ["🛶","canoe",""],["🚤","speedboat",""],["🛳️","passenger ship","tàu thuỷ"],["⛴️","ferry",""],
    ["🛥️","motor boat","động cơ thuyền"],["🚢","ship","tàu thuỷ"],["✈️","airplane","máy bay"],
    ["🛩️","small airplane","nhỏ máy bay"],["🛫","airplane departure","máy bay"],
    ["🛬","airplane arrival","máy bay"],["🪂","parachute",""],["💺","seat",""],["🚁","helicopter",""],
    ["🚟","suspension railway","đường sắt"],["🚠","mountain cableway","núi"],["🚡","aerial tramway",""],
    ["🛰️","satellite","vệ tinh"],["🚀","rocket",""],["🛸","flying saucer","bay"],["🛎️","bellhop bell","chuông"],
    ["🧳","luggage","hành lý"],["⌛","hourglass done","đồng hồ cát xong"],
    ["⏳","hourglass not done","đồng hồ cát không xong"],["⌚","watch",""],["⏰","alarm clock","đồng hồ"],
    ["⏱️","stopwatch",""],["⏲️","timer clock","đồng hồ"],["🕰️","mantelpiece clock","đồng hồ"],
    ["🕛","twelve o’clock","mười hai đồng hồ"],["🕧","twelve-thirty","mười hai rưỡi"],
    ["🕐","one o’clock","một đồng hồ"],["🕜","one-thirty","một rưỡi"],["🕑","two o’clock","hai đồng hồ"],
    ["🕝","two-thirty","hai rưỡi"],["🕒","three o’clock","ba đồng hồ"],["🕞","three-thirty","ba rưỡi"],
    ["🕓","four o’clock","bốn đồng hồ"],["🕟","four-thirty","bốn rưỡi"],["🕔","five o’clock","năm đồng hồ"],
    ["🕠","five-thirty","năm rưỡi"],["🕕","six o’clock","sáu đồng hồ"],["🕡","six-thirty","sáu rưỡi"],
    ["🕖","seven o’clock","bảy đồng hồ"],["🕢","seven-thirty","bảy rưỡi"],["🕗","eight o’clock","tám đồng hồ"],
    ["🕣","eight-thirty","tám rưỡi"],["🕘","nine o’clock","chín đồng hồ"],["🕤","nine-thirty","chín rưỡi"],
    ["🕙","ten o’clock","mười đồng hồ"],["🕥","ten-thirty","mười rưỡi"],["🕚","eleven o’clock","mười một đồng hồ"],
    ["🕦","eleven-thirty","mười một rưỡi"],["🌑","new moon","mới mặt trăng"],
    ["🌒","waxing crescent moon","trăng lên lưỡi liềm mặt"],
    ["🌓","first quarter moon","đầu tiên phần tư mặt trăng"],["🌔","waxing gibbous moon","trăng lên khuyết mặt"],
    ["🌕","full moon","tròn đầy mặt trăng"],["🌖","waning gibbous moon","trăng khuyết mặt"],
    ["🌗","last quarter moon","cuối phần tư mặt trăng"],["🌘","waning crescent moon","trăng khuyết lưỡi liềm mặt"],
    ["🌙","crescent moon","lưỡi liềm mặt trăng"],["🌚","new moon face","mới mặt trăng"],
    ["🌛","first quarter moon face","đầu tiên phần tư mặt trăng"],
    ["🌜","last quarter moon face","cuối phần tư mặt trăng"],["🌡️","thermometer","nhiệt kế"],
    ["☀️","sun","mặt trời"],["🌝","full moon face","tròn đầy mặt trăng"],["🌞","sun with face","mặt trời có"],
    ["🪐","ringed planet",""],["⭐","star","ngôi sao"],["🌟","glowing star","ngôi sao"],
    ["🌠","shooting star","ngôi sao"],["🌌","milky way",""],["☁️","cloud","mây"],
    ["⛅","sun behind cloud","mặt trời phía sau mây"],["⛈️","cloud with lightning and rain","mây có sét mưa"],
    ["🌤️","sun behind small cloud","mặt trời phía sau nhỏ mây"],
    ["🌥️","sun behind large cloud","mặt trời phía sau lớn mây"],
    ["🌦️","sun behind rain cloud","mặt trời phía sau mưa mây"],["🌧️","cloud with rain","mây có mưa"],
    ["🌨️","cloud with snow","mây có tuyết"],["🌩️","cloud with lightning","mây có sét"],["🌪️","tornado",""],
    ["🌫️","fog",""],["🌬️","wind face","gió mặt"],["🌀","cyclone",""],["🌈","rainbow",""],
    ["🌂","closed umbrella","đóng ô dù"],["☂️","umbrella","ô dù"],["☔","umbrella with rain drops","ô dù có mưa"],
    ["⛱️","umbrella on ground","ô dù bật"],["⚡","high voltage","cao"],["❄️","snowflake",""],
    ["☃️","snowman","người tuyết"],["⛄","snowman without snow","người tuyết không có"],["☄️","comet",""],
    ["🔥","fire","lửa"],["💧","droplet",""],["🌊","water wave","nước"]
  ]},
  { g: "Hoạt động", items: [
    ["🎃","jack-o-lantern","đèn lồng"],["🎄","Christmas tree","cây"],["🎆","fireworks",""],["🎇","sparkler",""],
    ["🧨","firecracker",""],["✨","sparkles",""],["🎈","balloon","bóng bay"],["🎉","party popper",""],
    ["🎊","confetti ball","bóng"],["🎋","tanabata tree","cây"],["🎍","pine decoration","trang trí"],
    ["🎎","Japanese dolls","nhật bản búp bê"],["🎏","carp streamer",""],["🎐","wind chime","gió"],
    ["🎑","moon viewing ceremony","mặt trăng"],["🧧","red envelope","đỏ phong bì"],["🎀","ribbon","nơ ruy băng"],
    ["🎁","wrapped gift",""],["🎗️","reminder ribbon","nơ ruy băng"],["🎟️","admission tickets",""],
    ["🎫","ticket",""],["🎖️","military medal","huy chương"],["🏆","trophy",""],["🏅","sports medal","huy chương"],
    ["🥇","1st place medal","nơi chốn huy chương"],["🥈","2nd place medal","nơi chốn huy chương"],
    ["🥉","3rd place medal","nơi chốn huy chương"],["⚽","soccer ball","bóng"],["⚾","baseball",""],
    ["🥎","softball",""],["🏀","basketball",""],["🏐","volleyball",""],["🏈","american football","bóng bầu dục"],
    ["🏉","rugby football","bóng bầu dục"],["🎾","tennis",""],["🥏","flying disc","bay"],["🎳","bowling",""],
    ["🏏","cricket game","dế trò chơi"],["🏑","field hockey","khúc côn cầu"],
    ["🏒","ice hockey","đá lạnh khúc côn cầu"],["🥍","lacrosse",""],["🏓","ping pong",""],["🏸","badminton",""],
    ["🥊","boxing glove",""],["🥋","martial arts uniform","nghệ thuật"],["🥅","goal net",""],
    ["⛳","flag in hole","cờ lỗ hổng"],["⛸️","ice skate","đá lạnh trượt"],["🎣","fishing pole","cột"],
    ["🤿","diving mask","khẩu trang"],["🎽","running shirt","chạy áo"],["🎿","skis",""],["🛷","sled",""],
    ["🥌","curling stone","đá"],["🎯","bullseye",""],["🪀","yo-yo",""],["🪁","kite",""],["🔫","water pistol","nước"],
    ["🎱","pool 8 ball","bóng"],["🔮","crystal ball","bóng"],["🪄","magic wand",""],
    ["🎮","video game","video trò chơi"],["🕹️","joystick",""],["🎰","slot machine","máy"],
    ["🎲","game die","trò chơi"],["🧩","puzzle piece",""],["🧸","teddy bear","gấu"],["🪅","piñata",""],
    ["🪩","mirror ball","gương bóng"],["🪆","nesting dolls","búp bê"],["♠️","spade suit","bộ vest"],
    ["♥️","heart suit","trái tim bộ vest"],["♦️","diamond suit","kim cương bộ vest"],
    ["♣️","club suit","bộ vest"],["♟️","chess pawn",""],["🃏","joker",""],["🀄","mahjong red dragon","đỏ rồng"],
    ["🎴","flower playing cards","hoa chơi"],["🎭","performing arts","nghệ thuật"],["🖼️","framed picture",""],
    ["🎨","artist palette","hoạ sĩ"],["🧵","thread",""],["🪡","sewing needle",""],["🧶","yarn",""],["🪢","knot",""]
  ]},
  { g: "Đồ vật", items: [
    ["👓","glasses","ly cốc"],["🕶️","sunglasses","kính râm"],["🥽","goggles",""],["🥼","lab coat","áo khoác"],
    ["🦺","safety vest","an toàn"],["👔","necktie",""],["👕","t-shirt","áo"],["👖","jeans",""],["🧣","scarf",""],
    ["🧤","gloves",""],["🧥","coat","áo khoác"],["🧦","socks",""],["👗","dress",""],["👘","kimono",""],
    ["🥻","sari",""],["🩱","one-piece swimsuit","một"],["🩲","briefs",""],["🩳","shorts",""],["👙","bikini",""],
    ["👚","woman’s clothes","phụ nữ đàn bà"],["🪭","folding hand fan","bàn tay"],["👛","purse",""],
    ["👜","handbag",""],["👝","clutch bag","túi"],["🛍️","shopping bags","mua sắm"],["🎒","backpack",""],
    ["🩴","thong sandal","dép"],["👞","man’s shoe","đàn ông người nam giày"],["👟","running shoe","chạy giày"],
    ["🥾","hiking boot","bốt"],["🥿","flat shoe","giày"],["👠","high-heeled shoe","cao giày"],
    ["👡","woman’s sandal","phụ nữ đàn bà dép"],["🩰","ballet shoes",""],["👢","woman’s boot","phụ nữ đàn bà bốt"],
    ["🪮","hair pick","tóc"],["👑","crown","vương miện"],["👒","woman’s hat","phụ nữ đàn bà mũ"],
    ["🎩","top hat","mũ"],["🎓","graduation cap","mũ lưỡi trai"],["🧢","billed cap","mũ lưỡi trai"],
    ["🪖","military helmet","mũ bảo hiểm"],["⛑️","rescue worker’s helmet","công nhân mũ bảo hiểm"],
    ["📿","prayer beads",""],["💄","lipstick",""],["💍","ring","nhẫn"],["💎","gem stone","đá"],
    ["🔇","muted speaker","loa"],["🔈","speaker low volume","loa thấp âm lượng"],
    ["🔉","speaker medium volume","loa vừa âm lượng"],["🔊","speaker high volume","loa cao âm lượng"],
    ["📢","loudspeaker",""],["📣","megaphone",""],["📯","postal horn",""],["🔔","bell","chuông"],
    ["🔕","bell with slash","chuông có"],["🎼","musical score","âm nhạc"],["🎵","musical note","âm nhạc"],
    ["🎶","musical notes","âm nhạc"],["🎙️","studio microphone","micro"],["🎚️","level slider",""],
    ["🎛️","control knobs","điều khiển"],["🎤","microphone","micro"],["🎧","headphone",""],["📻","radio","radio"],
    ["🎷","saxophone",""],["🪗","accordion",""],["🎸","guitar",""],["🎹","musical keyboard","âm nhạc bàn phím"],
    ["🎺","trumpet",""],["🎻","violin",""],["🪕","banjo",""],["🥁","drum","trống"],["🪘","long drum","trống"],
    ["🪇","maracas",""],["🪈","flute",""],["📱","mobile phone","di động điện thoại"],
    ["📲","mobile phone with arrow","di động điện thoại có mũi tên"],["☎️","telephone","điện thoại"],
    ["📞","telephone receiver","điện thoại"],["📟","pager",""],["📠","fax machine","máy"],["🔋","battery","pin"],
    ["🪫","low battery","thấp pin"],["🔌","electric plug",""],["💻","laptop",""],
    ["🖥️","desktop computer","máy tính"],["🖨️","printer",""],["⌨️","keyboard","bàn phím"],
    ["🖱️","computer mouse","máy tính chuột"],["🖲️","trackball",""],["💽","computer disk","máy tính đĩa"],
    ["💾","floppy disk","đĩa"],["💿","optical disk","đĩa"],["📀","dvd",""],["🧮","abacus",""],
    ["🎥","movie camera","máy ảnh"],["🎞️","film frames","phim"],["📽️","film projector","phim"],
    ["🎬","clapper board",""],["📺","television",""],["📷","camera","máy ảnh"],
    ["📸","camera with flash","máy ảnh có"],["📹","video camera","video máy ảnh"],["📼","videocassette",""],
    ["🔍","magnifying glass tilted left","kính lúp ly cốc trái"],
    ["🔎","magnifying glass tilted right","kính lúp ly cốc phải"],["🕯️","candle",""],
    ["💡","light bulb","nhạt sáng"],["🔦","flashlight",""],["🏮","red paper lantern","đỏ giấy đèn lồng"],
    ["🪔","diya lamp","đèn"],["📔","notebook with decorative cover","sổ tay có"],["📕","closed book","đóng sách"],
    ["📖","open book","mở sách"],["📗","green book","xanh lá sách"],["📘","blue book","xanh dương sách"],
    ["📙","orange book","cam sách"],["📚","books",""],["📓","notebook","sổ tay"],["📒","ledger",""],
    ["📃","page with curl","trang có"],["📜","scroll",""],["📄","page facing up","trang hướng lên"],
    ["📰","newspaper","báo"],["🗞️","rolled-up newspaper","lên báo"],["📑","bookmark tabs","đánh dấu trang"],
    ["🔖","bookmark","đánh dấu trang"],["🏷️","label",""],["💰","money bag","tiền túi"],["🪙","coin",""],
    ["💴","yen banknote","yên nhật tờ tiền"],["💵","dollar banknote","đô la tờ tiền"],
    ["💶","euro banknote","tờ tiền"],["💷","pound banknote","tờ tiền"],["💸","money with wings","tiền có"],
    ["💳","credit card","thẻ"],["🧾","receipt",""],
    ["💹","chart increasing with yen","biểu đồ tăng dần có yên nhật"],["✉️","envelope","phong bì"],
    ["📧","e-mail",""],["📨","incoming envelope","phong bì"],["📩","envelope with arrow","phong bì có mũi tên"],
    ["📤","outbox tray","khay"],["📥","inbox tray","khay"],["📦","package",""],
    ["📫","closed mailbox with raised flag","đóng hòm thư có giơ lên cờ"],
    ["📪","closed mailbox with lowered flag","đóng hòm thư có hạ xuống cờ"],
    ["📬","open mailbox with raised flag","mở hòm thư có giơ lên cờ"],
    ["📭","open mailbox with lowered flag","mở hòm thư có hạ xuống cờ"],["📮","postbox",""],
    ["🗳️","ballot box with ballot","phiếu bầu hộp có"],["✏️","pencil","bút chì"],["✒️","black nib","đen"],
    ["🖋️","fountain pen","đài phun nước bút"],["🖊️","pen","bút"],["🖌️","paintbrush",""],["🖍️","crayon",""],
    ["📝","memo",""],["💼","briefcase",""],["📁","file folder","tệp thư mục"],
    ["📂","open file folder","mở tệp thư mục"],["🗂️","card index dividers","thẻ ngón trỏ"],
    ["📅","calendar","lịch"],["📆","tear-off calendar","nước mắt tắt lịch"],["🗒️","spiral notepad","xoắn ốc"],
    ["🗓️","spiral calendar","xoắn ốc lịch"],["📇","card index","thẻ ngón trỏ"],
    ["📈","chart increasing","biểu đồ tăng dần"],["📉","chart decreasing","biểu đồ"],
    ["📊","bar chart","thanh biểu đồ"],["📋","clipboard",""],["📌","pushpin","ghim"],["📍","round pushpin","ghim"],
    ["📎","paperclip",""],["🖇️","linked paperclips",""],["📏","straight ruler","thước"],
    ["📐","triangular ruler","thước"],["✂️","scissors",""],["🗃️","card file box","thẻ tệp hộp"],
    ["🗄️","file cabinet","tệp"],["🗑️","wastebasket",""],["🔒","locked","khoá"],["🔓","unlocked",""],
    ["🔏","locked with pen","khoá có bút"],["🔐","locked with key","khoá có chìa"],["🔑","key","chìa khoá"],
    ["🗝️","old key","già chìa khoá"],["🔨","hammer","búa"],["🪓","axe",""],["⛏️","pick",""],
    ["⚒️","hammer and pick","búa"],["🛠️","hammer and wrench","búa cờ lê"],["🗡️","dagger",""],
    ["⚔️","crossed swords","bắt chéo"],["💣","bomb",""],["🪃","boomerang",""],["🏹","bow and arrow","mũi tên"],
    ["🛡️","shield",""],["🪚","carpentry saw",""],["🔧","wrench","cờ lê"],["🪛","screwdriver",""],
    ["🔩","nut and bolt",""],["⚙️","gear",""],["🗜️","clamp",""],["⚖️","balance scale",""],
    ["🦯","white cane","trắng gậy"],["🔗","link",""],["⛓️‍💥","broken chain",""],["⛓️","chains",""],["🪝","hook",""],
    ["🧰","toolbox",""],["🧲","magnet",""],["🪜","ladder",""],["⚗️","alembic",""],["🧪","test tube",""],
    ["🧫","petri dish",""],["🧬","dna",""],["🔬","microscope",""],["🔭","telescope",""],
    ["📡","satellite antenna","vệ tinh ăng ten"],["💉","syringe",""],["🩸","drop of blood","máu"],["💊","pill",""],
    ["🩹","adhesive bandage","băng gạc"],["🩼","crutch",""],["🩺","stethoscope",""],["🩻","x-ray",""],
    ["🚪","door",""],["🛗","elevator",""],["🪞","mirror","gương"],["🪟","window",""],["🛏️","bed","giường"],
    ["🛋️","couch and lamp","đèn"],["🪑","chair",""],["🚽","toilet",""],["🪠","plunger",""],["🚿","shower",""],
    ["🛁","bathtub",""],["🪤","mouse trap","chuột"],["🪒","razor",""],["🧴","lotion bottle","chai"],
    ["🧷","safety pin","an toàn"],["🧹","broom",""],["🧺","basket",""],["🧻","roll of paper","giấy"],
    ["🪣","bucket",""],["🧼","soap",""],["🫧","bubbles",""],["🪥","toothbrush",""],["🧽","sponge",""],
    ["🧯","fire extinguisher","lửa"],["🛒","shopping cart","mua sắm"],["🚬","cigarette",""],["⚰️","coffin",""],
    ["🪦","headstone",""],["⚱️","funeral urn",""],["🧿","nazar amulet",""],["🪬","hamsa",""],["🗿","moai",""],
    ["🪧","placard",""],["🪪","identification card","thẻ"]
  ]},
  { g: "Ký hiệu", items: [
    ["🏧","ATM sign","biển báo"],["🚮","litter in bin sign","biển báo"],["🚰","potable water","nước uống được"],
    ["♿","wheelchair symbol","xe lăn ký hiệu"],["🚹","men’s room","đàn ông phòng"],
    ["🚺","women’s room","phụ nữ phòng"],["🚻","restroom",""],["🚼","baby symbol","em bé ký hiệu"],
    ["🚾","water closet","nước"],["🛂","passport control","điều khiển"],["🛃","customs",""],
    ["🛄","baggage claim",""],["🛅","left luggage","trái hành lý"],["⚠️","warning",""],
    ["🚸","children crossing",""],["⛔","no entry","không"],["🚫","prohibited","cấm"],["🚳","no bicycles","không"],
    ["🚭","no smoking","không"],["🚯","no littering","không"],["🚱","non-potable water","nước uống được"],
    ["🚷","no pedestrians","không"],["📵","no mobile phones","không di động"],
    ["🔞","no one under eighteen","không một"],["☢️","radioactive",""],["☣️","biohazard",""],
    ["⬆️","up arrow","lên mũi tên"],["↗️","up-right arrow","lên phải mũi tên"],
    ["➡️","right arrow","phải mũi tên"],["↘️","down-right arrow","xuống phải mũi tên"],
    ["⬇️","down arrow","xuống mũi tên"],["↙️","down-left arrow","xuống trái mũi tên"],
    ["⬅️","left arrow","trái mũi tên"],["↖️","up-left arrow","lên trái mũi tên"],
    ["↕️","up-down arrow","lên xuống mũi tên"],["↔️","left-right arrow","trái phải mũi tên"],
    ["↩️","right arrow curving left","phải mũi tên trái"],["↪️","left arrow curving right","trái mũi tên phải"],
    ["⤴️","right arrow curving up","phải mũi tên lên"],["⤵️","right arrow curving down","phải mũi tên xuống"],
    ["🔃","clockwise vertical arrows","dọc mũi tên"],["🔄","counterclockwise arrows button","mũi tên nút"],
    ["🔙","BACK arrow","lùi mũi tên"],["🔚","END arrow","mũi tên"],["🔛","ON! arrow","bật mũi tên"],
    ["🔜","SOON arrow","mũi tên"],["🔝","TOP arrow","mũi tên"],["🛐","place of worship","nơi chốn"],
    ["⚛️","atom symbol","ký hiệu"],["🕉️","om",""],["✡️","star of David","ngôi sao"],
    ["☸️","wheel of dharma","bánh xe"],["☯️","yin yang",""],["✝️","latin cross","la tinh chữ thập"],
    ["☦️","orthodox cross","chữ thập"],["☪️","star and crescent","ngôi sao lưỡi liềm"],
    ["☮️","peace symbol","ký hiệu"],["🕎","menorah",""],["🔯","dotted six-pointed star","chấm sáu ngôi sao"],
    ["🪯","khanda",""],["♈","Aries",""],["♉","Taurus",""],["♊","Gemini",""],["♋","Cancer",""],["♌","Leo",""],
    ["♍","Virgo",""],["♎","Libra",""],["♏","Scorpio",""],["♐","Sagittarius",""],["♑","Capricorn",""],
    ["♒","Aquarius",""],["♓","Pisces",""],["⛎","Ophiuchus",""],["🔀","shuffle tracks button","nút"],
    ["🔁","repeat button","lặp lại nút"],["🔂","repeat single button","lặp lại nút"],
    ["▶️","play button","phát nút"],["⏩","fast-forward button","nhanh tiến nút"],
    ["⏭️","next track button","đường ray nút"],["⏯️","play or pause button","phát tạm dừng nút"],
    ["◀️","reverse button","đảo ngược nút"],["⏪","fast reverse button","nhanh đảo ngược nút"],
    ["⏮️","last track button","cuối đường ray nút"],["🔼","upwards button","nút"],
    ["⏫","fast up button","nhanh lên nút"],["🔽","downwards button","nút"],
    ["⏬","fast down button","nhanh xuống nút"],["⏸️","pause button","tạm dừng nút"],
    ["⏹️","stop button","dừng nút"],["⏺️","record button","nút"],["⏏️","eject button","nút"],["🎦","cinema",""],
    ["🔅","dim button","nút"],["🔆","bright button","nút"],["📶","antenna bars","ăng ten"],["🛜","wireless",""],
    ["📳","vibration mode",""],["📴","mobile phone off","di động điện thoại tắt"],["♀️","female sign","biển báo"],
    ["♂️","male sign","biển báo"],["⚧️","transgender symbol","ký hiệu"],["✖️","multiply",""],["➕","plus",""],
    ["➖","minus",""],["➗","divide",""],["🟰","heavy equals sign","đậm biển báo"],["♾️","infinity",""],
    ["‼️","double exclamation mark","đôi chấm than dấu"],["⁉️","exclamation question mark","chấm than hỏi dấu"],
    ["❓","red question mark","đỏ hỏi dấu"],["❔","white question mark","trắng hỏi dấu"],
    ["❕","white exclamation mark","trắng chấm than dấu"],["❗","red exclamation mark","đỏ chấm than dấu"],
    ["〰️","wavy dash",""],["💱","currency exchange",""],["💲","heavy dollar sign","đậm đô la biển báo"],
    ["⚕️","medical symbol","y tế ký hiệu"],["♻️","recycling symbol","ký hiệu"],["⚜️","fleur-de-lis",""],
    ["🔱","trident emblem",""],["📛","name badge",""],["🔰","Japanese symbol for beginner","nhật bản ký hiệu"],
    ["⭕","hollow red circle","đỏ tròn"],["✅","check mark button","dấu tích nút"],
    ["☑️","check box with check","dấu tích hộp có"],["✔️","check mark","dấu tích"],
    ["❌","cross mark","chữ thập dấu"],["❎","cross mark button","chữ thập dấu nút"],
    ["➰","curly loop","xoăn vòng lặp"],["➿","double curly loop","đôi xoăn vòng lặp"],
    ["〽️","part alternation mark","dấu"],["✳️","eight-spoked asterisk","tám"],
    ["✴️","eight-pointed star","tám ngôi sao"],["❇️","sparkle",""],["©️","copyright",""],["®️","registered",""],
    ["™️","trade mark","dấu"],["#️⃣","keycap: #","phím số"],["*️⃣","keycap: *","phím số"],
    ["0️⃣","keycap: 0","phím số"],["1️⃣","keycap: 1","phím số"],["2️⃣","keycap: 2","phím số"],
    ["3️⃣","keycap: 3","phím số"],["4️⃣","keycap: 4","phím số"],["5️⃣","keycap: 5","phím số"],
    ["6️⃣","keycap: 6","phím số"],["7️⃣","keycap: 7","phím số"],["8️⃣","keycap: 8","phím số"],
    ["9️⃣","keycap: 9","phím số"],["🔟","keycap: 10","phím số"],["🔠","input latin uppercase","nhập la tinh"],
    ["🔡","input latin lowercase","nhập la tinh"],["🔢","input numbers","nhập"],
    ["🔣","input symbols","nhập ký hiệu"],["🔤","input latin letters","nhập la tinh"],
    ["🅰️","A button (blood type)","nút máu loại"],["🆎","AB button (blood type)","nút máu loại"],
    ["🅱️","B button (blood type)","nút máu loại"],["🆑","CL button","nút"],["🆒","COOL button","nút"],
    ["🆓","FREE button","miễn phí nút"],["ℹ️","information",""],["🆔","ID button","nút"],["Ⓜ️","circled M",""],
    ["🆕","NEW button","mới nút"],["🆖","NG button","nút"],["🅾️","O button (blood type)","nút máu loại"],
    ["🆗","OK button","nút"],["🅿️","P button","nút"],["🆘","SOS button","nút"],["🆙","UP! button","lên nút"],
    ["🆚","VS button","nút"],["🈁","Japanese “here” button","nhật bản nút"],
    ["🈂️","Japanese “service charge” button","nhật bản dịch vụ sạc nút"],
    ["🈷️","Japanese “monthly amount” button","nhật bản nút"],
    ["🈶","Japanese “not free of charge” button","nhật bản không miễn phí sạc nút"],
    ["🈯","Japanese “reserved” button","nhật bản nút"],["🉐","Japanese “bargain” button","nhật bản nút"],
    ["🈹","Japanese “discount” button","nhật bản nút"],
    ["🈚","Japanese “free of charge” button","nhật bản miễn phí sạc nút"],
    ["🈲","Japanese “prohibited” button","nhật bản cấm nút"],["🉑","Japanese “acceptable” button","nhật bản nút"],
    ["🈸","Japanese “application” button","nhật bản nút"],["🈴","Japanese “passing grade” button","nhật bản nút"],
    ["🈳","Japanese “vacancy” button","nhật bản còn chỗ nút"],
    ["㊗️","Japanese “congratulations” button","nhật bản nút"],["㊙️","Japanese “secret” button","nhật bản nút"],
    ["🈺","Japanese “open for business” button","nhật bản mở nút"],
    ["🈵","Japanese “no vacancy” button","nhật bản không còn chỗ nút"],["🔴","red circle","đỏ tròn"],
    ["🟠","orange circle","cam tròn"],["🟡","yellow circle","vàng tròn"],["🟢","green circle","xanh lá tròn"],
    ["🔵","blue circle","xanh dương tròn"],["🟣","purple circle","tím tròn"],["🟤","brown circle","nâu tròn"],
    ["⚫","black circle","đen tròn"],["⚪","white circle","trắng tròn"],["🟥","red square","đỏ vuông"],
    ["🟧","orange square","cam vuông"],["🟨","yellow square","vàng vuông"],["🟩","green square","xanh lá vuông"],
    ["🟦","blue square","xanh dương vuông"],["🟪","purple square","tím vuông"],["🟫","brown square","nâu vuông"],
    ["⬛","black large square","đen lớn vuông"],["⬜","white large square","trắng lớn vuông"],
    ["◼️","black medium square","đen vừa vuông"],["◻️","white medium square","trắng vừa vuông"],
    ["◾","black medium-small square","đen vừa nhỏ vuông"],
    ["◽","white medium-small square","trắng vừa nhỏ vuông"],["▪️","black small square","đen nhỏ vuông"],
    ["▫️","white small square","trắng nhỏ vuông"],["🔶","large orange diamond","lớn cam kim cương"],
    ["🔷","large blue diamond","lớn xanh dương kim cương"],["🔸","small orange diamond","nhỏ cam kim cương"],
    ["🔹","small blue diamond","nhỏ xanh dương kim cương"],["🔺","red triangle pointed up","đỏ tam giác lên"],
    ["🔻","red triangle pointed down","đỏ tam giác xuống"],["💠","diamond with a dot","kim cương có"],
    ["🔘","radio button","radio nút"],["🔳","white square button","trắng vuông nút"],
    ["🔲","black square button","đen vuông nút"]
  ]},
  { g: "Cờ", items: [
    ["🏁","chequered flag","cờ"],["🚩","triangular flag","cờ"],["🎌","crossed flags","bắt chéo"],
    ["🏴","black flag","đen cờ"],["🏳️","white flag","trắng cờ"],["🏳️‍🌈","rainbow flag","cờ"],
    ["🏳️‍⚧️","transgender flag","cờ"],["🏴‍☠️","pirate flag","cờ"],
    ["🇦🇨","flag: Ascension Island","cờ Ascension Island"],["🇦🇩","flag: Andorra","cờ Andorra"],
    ["🇦🇪","flag: United Arab Emirates","cờ các tiểu vương quốc ả rập"],
    ["🇦🇫","flag: Afghanistan","cờ afghanistan"],["🇦🇬","flag: Antigua & Barbuda","cờ Antigua & Barbuda"],
    ["🇦🇮","flag: Anguilla","cờ Anguilla"],["🇦🇱","flag: Albania","cờ Albania"],
    ["🇦🇲","flag: Armenia","cờ Armenia"],["🇦🇴","flag: Angola","cờ angola"],
    ["🇦🇶","flag: Antarctica","cờ Antarctica"],["🇦🇷","flag: Argentina","cờ argentina"],
    ["🇦🇸","flag: American Samoa","cờ American Samoa"],["🇦🇹","flag: Austria","cờ áo"],
    ["🇦🇺","flag: Australia","cờ úc"],["🇦🇼","flag: Aruba","cờ Aruba"],
    ["🇦🇽","flag: Åland Islands","cờ Åland Islands"],["🇦🇿","flag: Azerbaijan","cờ Azerbaijan"],
    ["🇧🇦","flag: Bosnia & Herzegovina","cờ Bosnia & Herzegovina"],["🇧🇧","flag: Barbados","cờ Barbados"],
    ["🇧🇩","flag: Bangladesh","cờ bangladesh"],["🇧🇪","flag: Belgium","cờ bỉ"],
    ["🇧🇫","flag: Burkina Faso","cờ Burkina Faso"],["🇧🇬","flag: Bulgaria","cờ bulgaria"],
    ["🇧🇭","flag: Bahrain","cờ Bahrain"],["🇧🇮","flag: Burundi","cờ Burundi"],["🇧🇯","flag: Benin","cờ Benin"],
    ["🇧🇱","flag: St. Barthélemy","cờ St. Barthélemy"],["🇧🇲","flag: Bermuda","cờ Bermuda"],
    ["🇧🇳","flag: Brunei","cờ Brunei"],["🇧🇴","flag: Bolivia","cờ Bolivia"],
    ["🇧🇶","flag: Caribbean Netherlands","cờ Caribbean Netherlands"],["🇧🇷","flag: Brazil","cờ brazil"],
    ["🇧🇸","flag: Bahamas","cờ Bahamas"],["🇧🇹","flag: Bhutan","cờ Bhutan"],
    ["🇧🇻","flag: Bouvet Island","cờ Bouvet Island"],["🇧🇼","flag: Botswana","cờ Botswana"],
    ["🇧🇾","flag: Belarus","cờ belarus"],["🇧🇿","flag: Belize","cờ Belize"],["🇨🇦","flag: Canada","cờ canada"],
    ["🇨🇨","flag: Cocos (Keeling) Islands","cờ Cocos (Keeling) Islands"],
    ["🇨🇩","flag: Congo - Kinshasa","cờ Congo - Kinshasa"],
    ["🇨🇫","flag: Central African Republic","cờ Central African Republic"],
    ["🇨🇬","flag: Congo - Brazzaville","cờ Congo - Brazzaville"],["🇨🇭","flag: Switzerland","cờ thuỵ sĩ"],
    ["🇨🇮","flag: Côte d’Ivoire","cờ Côte d’Ivoire"],["🇨🇰","flag: Cook Islands","cờ Cook Islands"],
    ["🇨🇱","flag: Chile","cờ chile"],["🇨🇲","flag: Cameroon","cờ cameroon"],["🇨🇳","flag: China","cờ trung quốc"],
    ["🇨🇴","flag: Colombia","cờ colombia"],["🇨🇵","flag: Clipperton Island","cờ Clipperton Island"],
    ["🇨🇷","flag: Costa Rica","cờ Costa Rica"],["🇨🇺","flag: Cuba","cờ cuba"],
    ["🇨🇻","flag: Cape Verde","cờ Cape Verde"],["🇨🇼","flag: Curaçao","cờ Curaçao"],
    ["🇨🇽","flag: Christmas Island","cờ Christmas Island"],["🇨🇾","flag: Cyprus","cờ Cyprus"],
    ["🇨🇿","flag: Czechia","cờ séc"],["🇩🇪","flag: Germany","cờ đức"],
    ["🇩🇬","flag: Diego Garcia","cờ Diego Garcia"],["🇩🇯","flag: Djibouti","cờ Djibouti"],
    ["🇩🇰","flag: Denmark","cờ đan mạch"],["🇩🇲","flag: Dominica","cờ Dominica"],
    ["🇩🇴","flag: Dominican Republic","cờ Dominican Republic"],["🇩🇿","flag: Algeria","cờ algeria"],
    ["🇪🇦","flag: Ceuta & Melilla","cờ Ceuta & Melilla"],["🇪🇨","flag: Ecuador","cờ Ecuador"],
    ["🇪🇪","flag: Estonia","cờ estonia"],["🇪🇬","flag: Egypt","cờ ai cập"],
    ["🇪🇭","flag: Western Sahara","cờ Western Sahara"],["🇪🇷","flag: Eritrea","cờ Eritrea"],
    ["🇪🇸","flag: Spain","cờ tây ban nha"],["🇪🇹","flag: Ethiopia","cờ ethiopia"],
    ["🇪🇺","flag: European Union","cờ liên minh châu âu"],["🇫🇮","flag: Finland","cờ phần lan"],
    ["🇫🇯","flag: Fiji","cờ Fiji"],["🇫🇰","flag: Falkland Islands","cờ Falkland Islands"],
    ["🇫🇲","flag: Micronesia","cờ Micronesia"],["🇫🇴","flag: Faroe Islands","cờ Faroe Islands"],
    ["🇫🇷","flag: France","cờ pháp"],["🇬🇦","flag: Gabon","cờ Gabon"],["🇬🇧","flag: United Kingdom","cờ anh quốc"],
    ["🇬🇩","flag: Grenada","cờ Grenada"],["🇬🇪","flag: Georgia","cờ Georgia"],
    ["🇬🇫","flag: French Guiana","cờ French Guiana"],["🇬🇬","flag: Guernsey","cờ Guernsey"],
    ["🇬🇭","flag: Ghana","cờ ghana"],["🇬🇮","flag: Gibraltar","cờ Gibraltar"],
    ["🇬🇱","flag: Greenland","cờ Greenland"],["🇬🇲","flag: Gambia","cờ Gambia"],["🇬🇳","flag: Guinea","cờ Guinea"],
    ["🇬🇵","flag: Guadeloupe","cờ Guadeloupe"],["🇬🇶","flag: Equatorial Guinea","cờ Equatorial Guinea"],
    ["🇬🇷","flag: Greece","cờ hy lạp"],
    ["🇬🇸","flag: South Georgia & South Sandwich Islands","cờ South Georgia & South Sandwich Islands"],
    ["🇬🇹","flag: Guatemala","cờ Guatemala"],["🇬🇺","flag: Guam","cờ Guam"],
    ["🇬🇼","flag: Guinea-Bissau","cờ Guinea-Bissau"],["🇬🇾","flag: Guyana","cờ Guyana"],
    ["🇭🇰","flag: Hong Kong SAR China","cờ hồng kông"],
    ["🇭🇲","flag: Heard & McDonald Islands","cờ Heard & McDonald Islands"],["🇭🇳","flag: Honduras","cờ Honduras"],
    ["🇭🇷","flag: Croatia","cờ croatia"],["🇭🇹","flag: Haiti","cờ Haiti"],["🇭🇺","flag: Hungary","cờ hungary"],
    ["🇮🇨","flag: Canary Islands","cờ Canary Islands"],["🇮🇩","flag: Indonesia","cờ indonesia"],
    ["🇮🇪","flag: Ireland","cờ ireland"],["🇮🇱","flag: Israel","cờ israel"],
    ["🇮🇲","flag: Isle of Man","cờ Isle of Man"],["🇮🇳","flag: India","cờ ấn độ"],
    ["🇮🇴","flag: British Indian Ocean Territory","cờ British Indian Ocean Territory"],
    ["🇮🇶","flag: Iraq","cờ iraq"],["🇮🇷","flag: Iran","cờ iran"],["🇮🇸","flag: Iceland","cờ iceland"],
    ["🇮🇹","flag: Italy","cờ ý"],["🇯🇪","flag: Jersey","cờ Jersey"],["🇯🇲","flag: Jamaica","cờ Jamaica"],
    ["🇯🇴","flag: Jordan","cờ jordan"],["🇯🇵","flag: Japan","cờ nhật bản"],["🇰🇪","flag: Kenya","cờ kenya"],
    ["🇰🇬","flag: Kyrgyzstan","cờ Kyrgyzstan"],["🇰🇭","flag: Cambodia","cờ campuchia"],
    ["🇰🇮","flag: Kiribati","cờ Kiribati"],["🇰🇲","flag: Comoros","cờ Comoros"],
    ["🇰🇳","flag: St. Kitts & Nevis","cờ St. Kitts & Nevis"],["🇰🇵","flag: North Korea","cờ triều tiên"],
    ["🇰🇷","flag: South Korea","cờ hàn quốc"],["🇰🇼","flag: Kuwait","cờ kuwait"],
    ["🇰🇾","flag: Cayman Islands","cờ Cayman Islands"],["🇰🇿","flag: Kazakhstan","cờ kazakhstan"],
    ["🇱🇦","flag: Laos","cờ lào"],["🇱🇧","flag: Lebanon","cờ liban"],["🇱🇨","flag: St. Lucia","cờ St. Lucia"],
    ["🇱🇮","flag: Liechtenstein","cờ Liechtenstein"],["🇱🇰","flag: Sri Lanka","cờ sri lanka"],
    ["🇱🇷","flag: Liberia","cờ Liberia"],["🇱🇸","flag: Lesotho","cờ Lesotho"],["🇱🇹","flag: Lithuania","cờ litva"],
    ["🇱🇺","flag: Luxembourg","cờ Luxembourg"],["🇱🇻","flag: Latvia","cờ latvia"],["🇱🇾","flag: Libya","cờ libya"],
    ["🇲🇦","flag: Morocco","cờ ma rốc"],["🇲🇨","flag: Monaco","cờ Monaco"],["🇲🇩","flag: Moldova","cờ Moldova"],
    ["🇲🇪","flag: Montenegro","cờ Montenegro"],["🇲🇫","flag: St. Martin","cờ St. Martin"],
    ["🇲🇬","flag: Madagascar","cờ Madagascar"],["🇲🇭","flag: Marshall Islands","cờ Marshall Islands"],
    ["🇲🇰","flag: North Macedonia","cờ North Macedonia"],["🇲🇱","flag: Mali","cờ Mali"],
    ["🇲🇲","flag: Myanmar (Burma)","cờ myanmar mien dien"],["🇲🇳","flag: Mongolia","cờ mông cổ"],
    ["🇲🇴","flag: Macao SAR China","cờ ma cao"],
    ["🇲🇵","flag: Northern Mariana Islands","cờ Northern Mariana Islands"],
    ["🇲🇶","flag: Martinique","cờ Martinique"],["🇲🇷","flag: Mauritania","cờ Mauritania"],
    ["🇲🇸","flag: Montserrat","cờ Montserrat"],["🇲🇹","flag: Malta","cờ Malta"],
    ["🇲🇺","flag: Mauritius","cờ Mauritius"],["🇲🇻","flag: Maldives","cờ Maldives"],
    ["🇲🇼","flag: Malawi","cờ Malawi"],["🇲🇽","flag: Mexico","cờ mexico"],["🇲🇾","flag: Malaysia","cờ malaysia"],
    ["🇲🇿","flag: Mozambique","cờ mozambique"],["🇳🇦","flag: Namibia","cờ Namibia"],
    ["🇳🇨","flag: New Caledonia","cờ New Caledonia"],["🇳🇪","flag: Niger","cờ Niger"],
    ["🇳🇫","flag: Norfolk Island","cờ Norfolk Island"],["🇳🇬","flag: Nigeria","cờ nigeria"],
    ["🇳🇮","flag: Nicaragua","cờ Nicaragua"],["🇳🇱","flag: Netherlands","cờ hà lan"],
    ["🇳🇴","flag: Norway","cờ na uy"],["🇳🇵","flag: Nepal","cờ nepal"],["🇳🇷","flag: Nauru","cờ Nauru"],
    ["🇳🇺","flag: Niue","cờ Niue"],["🇳🇿","flag: New Zealand","cờ new zealand"],["🇴🇲","flag: Oman","cờ oman"],
    ["🇵🇦","flag: Panama","cờ Panama"],["🇵🇪","flag: Peru","cờ peru"],
    ["🇵🇫","flag: French Polynesia","cờ French Polynesia"],["🇵🇬","flag: Papua New Guinea","cờ Papua New Guinea"],
    ["🇵🇭","flag: Philippines","cờ philippines"],["🇵🇰","flag: Pakistan","cờ pakistan"],
    ["🇵🇱","flag: Poland","cờ ba lan"],["🇵🇲","flag: St. Pierre & Miquelon","cờ St. Pierre & Miquelon"],
    ["🇵🇳","flag: Pitcairn Islands","cờ Pitcairn Islands"],["🇵🇷","flag: Puerto Rico","cờ Puerto Rico"],
    ["🇵🇸","flag: Palestinian Territories","cờ Palestinian Territories"],["🇵🇹","flag: Portugal","cờ bồ đào nha"],
    ["🇵🇼","flag: Palau","cờ Palau"],["🇵🇾","flag: Paraguay","cờ Paraguay"],["🇶🇦","flag: Qatar","cờ qatar"],
    ["🇷🇪","flag: Réunion","cờ Réunion"],["🇷🇴","flag: Romania","cờ romania"],["🇷🇸","flag: Serbia","cờ serbia"],
    ["🇷🇺","flag: Russia","cờ nga"],["🇷🇼","flag: Rwanda","cờ Rwanda"],
    ["🇸🇦","flag: Saudi Arabia","cờ ả rập xê út"],["🇸🇧","flag: Solomon Islands","cờ Solomon Islands"],
    ["🇸🇨","flag: Seychelles","cờ Seychelles"],["🇸🇩","flag: Sudan","cờ sudan"],
    ["🇸🇪","flag: Sweden","cờ thuỵ điển"],["🇸🇬","flag: Singapore","cờ singapore"],
    ["🇸🇭","flag: St. Helena","cờ St. Helena"],["🇸🇮","flag: Slovenia","cờ slovenia"],
    ["🇸🇯","flag: Svalbard & Jan Mayen","cờ Svalbard & Jan Mayen"],["🇸🇰","flag: Slovakia","cờ slovakia"],
    ["🇸🇱","flag: Sierra Leone","cờ Sierra Leone"],["🇸🇲","flag: San Marino","cờ San Marino"],
    ["🇸🇳","flag: Senegal","cờ senegal"],["🇸🇴","flag: Somalia","cờ Somalia"],
    ["🇸🇷","flag: Suriname","cờ Suriname"],["🇸🇸","flag: South Sudan","cờ South Sudan"],
    ["🇸🇹","flag: São Tomé & Príncipe","cờ São Tomé & Príncipe"],["🇸🇻","flag: El Salvador","cờ El Salvador"],
    ["🇸🇽","flag: Sint Maarten","cờ Sint Maarten"],["🇸🇾","flag: Syria","cờ syria"],
    ["🇸🇿","flag: Eswatini","cờ Eswatini"],["🇹🇦","flag: Tristan da Cunha","cờ Tristan da Cunha"],
    ["🇹🇨","flag: Turks & Caicos Islands","cờ Turks & Caicos Islands"],["🇹🇩","flag: Chad","cờ Chad"],
    ["🇹🇫","flag: French Southern Territories","cờ French Southern Territories"],["🇹🇬","flag: Togo","cờ Togo"],
    ["🇹🇭","flag: Thailand","cờ thái lan"],["🇹🇯","flag: Tajikistan","cờ Tajikistan"],
    ["🇹🇰","flag: Tokelau","cờ Tokelau"],["🇹🇱","flag: Timor-Leste","cờ Timor-Leste"],
    ["🇹🇲","flag: Turkmenistan","cờ Turkmenistan"],["🇹🇳","flag: Tunisia","cờ tunisia"],
    ["🇹🇴","flag: Tonga","cờ Tonga"],["🇹🇷","flag: Türkiye","cờ Türkiye"],
    ["🇹🇹","flag: Trinidad & Tobago","cờ Trinidad & Tobago"],["🇹🇻","flag: Tuvalu","cờ Tuvalu"],
    ["🇹🇼","flag: Taiwan","cờ đài loan"],["🇹🇿","flag: Tanzania","cờ tanzania"],
    ["🇺🇦","flag: Ukraine","cờ ukraina"],["🇺🇬","flag: Uganda","cờ uganda"],
    ["🇺🇲","flag: U.S. Outlying Islands","cờ U.S. Outlying Islands"],
    ["🇺🇳","flag: United Nations","cờ liên hợp quốc"],["🇺🇸","flag: United States","cờ mỹ hoa kỳ"],
    ["🇺🇾","flag: Uruguay","cờ Uruguay"],["🇺🇿","flag: Uzbekistan","cờ uzbekistan"],
    ["🇻🇦","flag: Vatican City","cờ Vatican City"],
    ["🇻🇨","flag: St. Vincent & Grenadines","cờ St. Vincent & Grenadines"],
    ["🇻🇪","flag: Venezuela","cờ venezuela"],["🇻🇬","flag: British Virgin Islands","cờ British Virgin Islands"],
    ["🇻🇮","flag: U.S. Virgin Islands","cờ U.S. Virgin Islands"],["🇻🇳","flag: Vietnam","cờ việt nam"],
    ["🇻🇺","flag: Vanuatu","cờ Vanuatu"],["🇼🇫","flag: Wallis & Futuna","cờ Wallis & Futuna"],
    ["🇼🇸","flag: Samoa","cờ Samoa"],["🇽🇰","flag: Kosovo","cờ Kosovo"],["🇾🇪","flag: Yemen","cờ yemen"],
    ["🇾🇹","flag: Mayotte","cờ Mayotte"],["🇿🇦","flag: South Africa","cờ nam phi"],
    ["🇿🇲","flag: Zambia","cờ zambia"],["🇿🇼","flag: Zimbabwe","cờ zimbabwe"],
    ["🏴󠁧󠁢󠁥󠁮󠁧󠁿","flag: England","cờ England"],["🏴󠁧󠁢󠁳󠁣󠁴󠁿","flag: Scotland","cờ Scotland"],
    ["🏴󠁧󠁢󠁷󠁬󠁳󠁿","flag: Wales","cờ Wales"]
  ]}
];
var EMOJI_TONG = 1898;
